//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qltv_lg.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-M34S7SI\\SQLEXPRESS;Initial Catalog=QLTVMATTERByHPXC_2;Integra" +
            "ted Security=True;TrustServerCertificate=True")]
        public string QLTVMATTERByHPXC_2ConnectionString {
            get {
                return ((string)(this["QLTVMATTERByHPXC_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9RFV7QR\\SQLEXPRESS;Initial Catalog=QLTVMATTERByHPXC;Persist S" +
            "ecurity Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Applicat" +
            "ion Name=EntityFramework")]
        public string QLTVMATTERByHPXCConnectionString {
            get {
                return ((string)(this["QLTVMATTERByHPXCConnectionString"]));
            }
        }
    }
}
